### ISSUE TITLE
main.py references several items not found

### ISSUE THREAD

**Issue by jason11758** [chrisdruta/rnn-crypto-trader#1]
in main.py the below is missing code to run properly
stock_game is not found

# Run hypothetical investment scenarios and write results to file
most_stocks, most_money = **stock_game**(inv_y, real, 10000)
predicted_stocks, predicted_money = stock_game(inv_y, pred, 10000)
with open("./output/{}.txt".format(filename), "w") as f:
    f.write("Possible stocks and money: %.2f\t$%.2f\n" % (most_stocks, most_money))
    f.write("Predicted stocks and money: %.2f\t$%.2f" % (predicted_stocks, predicted_money))
print("Total stocks and money: %.2f\t$%.2f" % (most_stocks, most_money))
print("Predicted stocks and money: %.2f\t$%.2f" % (predicted_stocks, predicted_money))

**Comment by chrisdruta** [comment]
Hi jason! I scrapped this code from a school project I worked on and haven't decided how I want to test investment gains so I'll just remove it for now.

**Comment by jason11758** [comment]
Oh okay, I thought it was just something else you had going on.

Im always looking for different ways to test crypto price predictions.
